[project]
name = "mdlt-er"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.12.0",
    "bitsandbytes>=0.49.1",
    "peft>=0.18.1",
    "pillow>=12.1.1",
    "torch>=2.7.0",
    "transformers>=4.51.1",
]
